### ISSUE TITLE
Doesn't work, spams an error message in log

### ISSUE THREAD

**Issue by NextNepper** [CrimsonMods/AutoBrazier#1]
It is spamming this message in log:
```
[Info   :AutoBrazier] 2024-07-14 04:29:17Z: [Core] Returning because either Plugin.AutoToggleEnabled is False (True) or Core.HasInitialized is False False)
```
Downgrading required mod(BloodyCore) from version 1.2.4 to 1.2.2 makes it work correctly and stops the error message. AutoBrazier probably needs to be updated to be compatible with BloodyCore again.

**Comment by Ryonez** [comment]
Why was this closed? It's still a current issue.

**Comment by NextNepper** [comment]
> Why was this closed? It's still a current issue.

Someone (developer of the mod?) shared a version that fixes this issue on discord server. I don't remember why I closed this issue(since it was a few months ago) but that's probably the reason. But I am not sure if that "discord version" is broken again, I haven't played the game for quite a while.

**Comment by Ryonez** [comment]
Ah, thank you, both for the info and reopening.

I reached out here as this is the exact error I had yesterday, it'd spammed the logs quite badly.
However after looking into it and restarting the sever it's been giving another error (from bloodycore related to this plugin, `AutoBrazier.Server.AutoToggle.PlayerDisconnected`).

I'll keep an eye on that, and if that one persists/has an issue in game I'll likely make a new issue for that.
No idea what happened to the False error, maybe this was the start of the problem and I didn't see it before the spam.

**Comment by SkyTech6** [comment]
It would be helpful if you posted your logfile showing the exact exception stack @Ryonez 

Aside from that, I have mainly quit personal V Rising modding and only return on commissions. So it's unlikely I will personally be updating this mod; although it's always open to pull requests from the community. 

~ That aside, I might eventually remove the BloodyCore and Bloodstone dependencies... I just don't like having dependencies on other mods if avoidable.

**Comment by Ryonez** [comment]
```
[Message: Preloader] BepInEx 6.0.0-be.691 - VRisingServer
[Message: Preloader] Built from commit 3ba398f269961fe6721f918423df399d0b481d7e
[Info   :   BepInEx] System platform: Windows 10 (Wine 9.0) 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2022.3.23f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 7 plugins to load
[Info   :   BepInEx] Loading [VampireCommandFramework 0.9.0]
[Message:VampireCommandFramework] VCF Loaded: 0.9.0
[Info   :   BepInEx] Loading [Bloodstone 0.2.2]
[Info   :Il2CppInterop] Registered mono type Bloodstone.Hooks.GameFrame in il2cpp domain
[Info   :Bloodstone] Detouring NetworkEvents_Serialize.SerializeEvent at 6FFFF2504FD0
[Info   :Bloodstone] Detouring NetworkEvents_Serialize.DeserializeEvent at 6FFFF13C03A0
[Info   :Bloodstone] Bloodstone v0.2.2 loaded.
[Info   :   BepInEx] Loading [AutoBrazier 0.2.1]
[Info   :AutoBrazier] 2024-12-03 10:51:02Z: [Core] Plugin AutoBrazier version 0.2.1 is Loading!
[Info   :AutoBrazier] 2024-12-03 10:51:02Z: [Core] Plugin AutoBrazier version 0.2.1 is loaded!
[Info   :   BepInEx] Loading [AutoCloseDoors 2.0.2]
[Info   :AutoCloseDoors] Plugin AutoCloseDoors version 2.0.2 is loaded!
[Info   :   BepInEx] Loading [Bloody.Core 1.2.5]
[Info   :Bloody.Core] [10:51:02] Load Systems for Server
[Info   :Bloody.Core] [10:51:02] Plugin trodi.Bloody.Core version 1.2.5 is loaded!
[Info   :   BepInEx] Loading [BloodyNotify 3.0.10]
[Info   :BloodyNotify] [10:51:02] Plugin BloodyNotify version 3.0.10 is loaded!
[Info   :   BepInEx] Loading [KindredLogistics 1.2.0]
[Info   :KindredLogistics] Plugin KindredLogistics version 1.2.0 is loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   :Bloodstone] Game has bootstrapped. Worlds and systems now exist.
[Info   :AutoBrazier] InitializeAfterLoaded completed
[Info   :Bloody.Core] [10:51:15] OnCoreInitialized is loaded!
[Info   :Il2CppInterop] Registered mono type BepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumerator in il2cpp domain
[Info   :Bloody.Core] [10:51:15] OnCoreInitialized is loaded!
[Info   :KindredLogistics] KindredLogistics initialized
[Error  :Bloody.Core] [10:51:25] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Il2CppInterop.Runtime.Il2CppException: System.Collections.Generic.KeyNotFoundException: The given key '{Steam 386092932}' was not present in the dictionary.
--- BEGIN IL2CPP STACK TRACE ---
System.Collections.Generic.KeyNotFoundException: The given key '{Steam 386092932}' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.ServerNetworkLayer.OnUserDisconnected (Stunlock.Network.ConnectionStatusChangeReason changeReason, Stunlock.Network.NetConnectionId netConnectionId, System.String extraData) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.Steam.ServerSteamTransportLayer.CloseConnection (Stunlock.Network.Steam.ServerSteamTransportLayer+ConnectionData connectionData, Stunlock.Network.ConnectionStatusChangeReason notifyRemoteReason, System.Boolean enableLinger, System.String debugMessage) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.Steam.ServerSteamTransportLayer.Disconnect (Stunlock.Network.NetConnectionId netConnectionId, Stunlock.Network.ConnectionStatusChangeReason reason, System.String extraMessage) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.ServerNetworkLayer.Deny (Stunlock.Network.NetConnectionId netConnectionId, Stunlock.Network.ConnectionStatusChangeReason reason, System.String extraMessage) [0x00000] in <00000000000000000000000000000000>:0 
  at ProjectM.ServerBootstrapSystem.OnConnectionApproval (Stunlock.Network.NetBufferIn& netBufferIn, Stunlock.Network.NetConnectionId netConnectionId) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.ServerNetworkLayer.OnDataReceived (Stunlock.Network.NetBufferIn& incomingMessage, Stunlock.Network.NetConnectionId netConnectionId) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.Steam.ServerSteamTransportLayer.ProcessNewMessages () [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.Steam.ServerSteamTransportLayer.Update (System.Double timeNow) [0x00000] in <00000000000000000000000000000000>:0 
  at ProjectM.ServerBootstrapSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.SystemBase.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.SystemBase.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.SystemBase.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.TimeableComponentSystemGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.SystemBase.Update () [0x00000] in <00000000000000000000000000000000>:0 
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Il2CppException.cs:line 36
   at Il2CppSystem.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoBrazier.Server.AutoToggle.PlayerDisconnected(ServerBootstrapSystem bootstrapSystem, NetConnectionId player, ConnectionStatusChangeReason reason, String extraData)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Bloody.Core.API.v1.EventsHandlerSystem.OnUserDisconnectedInvoke(ServerBootstrapSystem sender, NetConnectionId netConnectionId, ConnectionStatusChangeReason connectionStatusReason, String extraData)
[Info   :BloodyNotify] [10:51:43] ha conectado Ryonia 
[Info   :BloodyNotify] [11:21:31] ha conectado Thornrose 
[Error  :Bloody.Core] [12:24:54] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Il2CppInterop.Runtime.Il2CppException: System.Collections.Generic.KeyNotFoundException: The given key '{Steam 2796658299}' was not present in the dictionary.
--- BEGIN IL2CPP STACK TRACE ---
System.Collections.Generic.KeyNotFoundException: The given key '{Steam 2796658299}' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.ServerNetworkLayer.OnUserDisconnected (Stunlock.Network.ConnectionStatusChangeReason changeReason, Stunlock.Network.NetConnectionId netConnectionId, System.String extraData) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.Steam.ServerSteamTransportLayer.CloseConnection (Stunlock.Network.Steam.ServerSteamTransportLayer+ConnectionData connectionData, Stunlock.Network.ConnectionStatusChangeReason notifyRemoteReason, System.Boolean enableLinger, System.String debugMessage) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.Steam.ServerSteamTransportLayer.Disconnect (Stunlock.Network.NetConnectionId netConnectionId, Stunlock.Network.ConnectionStatusChangeReason reason, System.String extraMessage) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.ServerNetworkLayer.Deny (Stunlock.Network.NetConnectionId netConnectionId, Stunlock.Network.ConnectionStatusChangeReason reason, System.String extraMessage) [0x00000] in <00000000000000000000000000000000>:0 
  at ProjectM.ServerBootstrapSystem.OnConnectionApproval (Stunlock.Network.NetBufferIn& netBufferIn, Stunlock.Network.NetConnectionId netConnectionId) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.ServerNetworkLayer.OnDataReceived (Stunlock.Network.NetBufferIn& incomingMessage, Stunlock.Network.NetConnectionId netConnectionId) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.Steam.ServerSteamTransportLayer.ProcessNewMessages () [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Network.Steam.ServerSteamTransportLayer.Update (System.Double timeNow) [0x00000] in <00000000000000000000000000000000>:0 
  at ProjectM.ServerBootstrapSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.SystemBase.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.SystemBase.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.SystemBase.Update () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.UpdateAllSystems () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.TimeableComponentSystemGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.SystemBase.Update () [0x00000] in <00000000000000000000000000000000>:0 
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Il2CppException.cs:line 36
   at Il2CppSystem.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoBrazier.Server.AutoToggle.PlayerDisconnected(ServerBootstrapSystem bootstrapSystem, NetConnectionId player, ConnectionStatusChangeReason reason, String extraData)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Bloody.Core.API.v1.EventsHandlerSystem.OnUserDisconnectedInvoke(ServerBootstrapSystem sender, NetConnectionId netConnectionId, ConnectionStatusChangeReason connectionStatusReason, String extraData)
[Info   :BloodyNotify] [12:25:13] ha conectado Ryonia 
```

This is what it gave me.

And yeah, dependencies can be helpful, but they can also add a lot of bloat and complexity.

Atm I wouldn't be able to submit a pr myself, I'd have to go over the code and figure out how it's working together, and I haven't touched mod code for vrising before. So would take a while.

**Comment by SkyTech6** [comment]
You're using v1.2.5 of BloodyCore. Not sure where that's from as both GitHub and Thunderstore are v1.2.4. 

But this mod supports v1.2.4, please downgrade your Core.

**Comment by SkyTech6** [comment]
[AutoBrazier.zip](https://github.com/user-attachments/files/18010144/AutoBrazier.zip)

Here you go. Try this. Removed Dependencies on both Bloodstone and Bloody.Core.

**Comment by Ryonez** [comment]
Didn't work sorry, seems like somethings a bit off. Spams the log with this:
```
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoBrazier.Hooks.BonfirePatch.OnUpdate(BonfireSystemUpdateCloud __instance)
   at DMD<ProjectM.BonfireSystemUpdateCloud::OnUpdate>(BonfireSystemUpdateCloud this)
   at (il2cpp -> managed) OnUpdate(IntPtr , Il2CppMethodInfo* )
   ```

**Comment by SkyTech6** [comment]
https://github.com/CrimsonMods/AutoBrazier/releases/tag/v1.0.2

Ah. I rushed in removing the dependencies and deleted a needed function call. Try this one.

**Comment by Ryonez** [comment]
There's now no error when it loads up, but the braziers don't toggle with the day/night cycle. Also with no errors.
